### PR TITLE
Add apiVersion in ChatModelProperties

### PR DESCRIPTION
**Pull request by omebarki**
Add apiVersion in ChatModelProperties in order to append api-version in HTTP request parameter

### CODE REVIEW

**Comment by langchain4j** [comment]
@omebarki why is this required?

**Comment by omebarki** [comment]
In some cases to reach the model the URL should be something like : https://..../chat/completions?api-version=2024-02-15-preview
Otherwise I have a not found error :

{
    "error": {
        "code": "404",
        "message": "Resource not found"
    }
}

**Comment by langchain4j** [comment]
What LLM provider is this for?

**Comment by omebarki** [comment]
Entreprise azure openai

**Comment by langchain4j** [comment]
Then this should be added to `langchain4j-azure-open-ai-spring-boot-starter` then.
`AzureOpenAiChatModel` has a `serviceVersion` property which can be added to the SB starter.

**Comment by omebarki** [comment]
Even in dev.langchain4j.azure.openai.spring.ChatModelProperties we don't have neither serviceVersion nor apiVersion.
In my understanding, if its not present in ChatModelProperties classes, it won't be propagated to the AzureOpenAiChatModel

**Comment by langchain4j** [comment]
@omebarki correct, `dev.langchain4j.azure.openai.spring.ChatModelProperties` should be extended

**Comment by langchain4j** [comment]
@omebarki I've added missing properties (including `serviceVersion`) in https://github.com/langchain4j/langchain4j-spring/commit/59df6a95f680d93f98b672e233866cfadfdff697, so I will close this PR

**Pull request closed without merging**
