### PR TITLE
add AiServiceRegisteredEvent

### PR DESCRIPTION
**Pull request by catofdestruction**
Publish a Spring Event after registering the AiService Bean in AiServicesAutoConfig.
This event contains the AiService class and its corresponding tools description information.

Once a user implements the AiServiceRegisteredEventListener to listen for this event, they can receive the event during the Spring Boot startup phase and handle their business logic as needed.

Issues link: https://github.com/langchain4j/langchain4j/issues/2112

### CODE REVIEW

**Comment by catofdestruction** [comment]
> @catofdestruction thanks a lot! I will review it asap during this week

 It seems there is a conflict with another branch’s commits. How should I handle this conflict?

**Comment by langchain4j** [comment]
@catofdestruction could you please try to resolve the conflict? You will probably need to manually merge changes from both branches.

**Comment by catofdestruction** [comment]
> @catofdestruction could you please try to resolve the conflict? You will probably need to manually merge changes from both branches.

I tried to perform the merge in the browser, but I’m not sure if it can compile successfully, and whether the unit tests can run properly.

https://github.com/langchain4j/langchain4j-spring/pull/80
Additionally, has this commit been correctly merged into the main branch?
If it has been completed, can I sync my fork from the main branch again and submit a new PR?

**Comment by catofdestruction** [comment]
> @catofdestruction could you please try to resolve the conflict? You will probably need to manually merge changes from both branches.

Additionally, I also found these errors, but I don’t know how to resolve them  :(

image

image

**Comment by langchain4j** [comment]
Please ignore those failures in the CI build, they happen because API keys do not propagate to your branch.

But `should_receive_ai_service_registered_event` is failing, could you pelase check?

> [AiServiceWithTools]: [Tool-1]: ToolSpecification { name = "getCurrentDate", description = null, parameters = null, toolParameters = null }
> [AiServiceWithTools]: [Tool-2]: ToolSpecification { name = "getCurrentTime", description = null, parameters = null, toolParameters = null }
> [AiServiceWithTools]: [Tool-3]: ToolSpecification { name = "getToolObserverKey", description = "Find the key name of @ToolObserver", parameters = null, toolParameters = null }
> 
> org.opentest4j.AssertionFailedError: 
> Expected :2
> Actual   :3
> <Click to see difference>
> 
> 
> 	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
> 	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
> 	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
> 	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
> 	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
> 	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
> 	at dev.langchain4j.service.spring.mode.automatic.withTools.AiServicesAutoConfigIT.lambda$should_receive_ai_service_registered_event$2(AiServicesAutoConfigIT.java:94)
> 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.accept(AbstractApplicationContextRunner.java:434)
> 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.consumeAssertableContext(AbstractApplicationContextRunner.java:363)
> 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$run$0(AbstractApplicationContextRunner.java:341)
> 	at org.springframework.boot.test.util.TestPropertyValues.lambda$applyToSystemProperties$1(TestPropertyValues.java:174)
> 	at org.springframework.boot.test.util.TestPropertyValues.applyToSystemProperties(TestPropertyValues.java:188)
> 	at org.springframework.boot.test.util.TestPropertyValues.applyToSystemProperties(TestPropertyValues.java:173)
> 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$run$1(AbstractApplicationContextRunner.java:341)
> 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.withContextClassLoader(AbstractApplicationContextRunner.java:369)
> 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.run(AbstractApplicationContextRunner.java:340)
> 	at dev.langchain4j.service.spring.mode.automatic.withTools.AiServicesAutoConfigIT.should_receive_ai_service_registered_event(AiServicesAutoConfigIT.java:82)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
> 
>

**Comment by catofdestruction** [comment]
> Please ignore those failures in the CI build, they happen because API keys do not propagate to your branch.
> 
> But `should_receive_ai_service_registered_event` is failing, could you pelase check?
> 
> > [AiServiceWithTools]: [Tool-1]: ToolSpecification { name = "getCurrentDate", description = null, parameters = null, toolParameters = null }
> > [AiServiceWithTools]: [Tool-2]: ToolSpecification { name = "getCurrentTime", description = null, parameters = null, toolParameters = null }
> > [AiServiceWithTools]: [Tool-3]: ToolSpecification { name = "getToolObserverKey", description = "Find the key name of @ToolObserver", parameters = null, toolParameters = null }
> > org.opentest4j.AssertionFailedError:
> > Expected :2
> > Actual   :3
> > 
> > at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
> > at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
> > at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
> > at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
> > at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
> > at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
> > at dev.langchain4j.service.spring.mode.automatic.withTools.AiServicesAutoConfigIT.lambda$should_receive_ai_service_registered_event$2(AiServicesAutoConfigIT.java:94)
> > at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.accept(AbstractApplicationContextRunner.java:434)
> > at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.consumeAssertableContext(AbstractApplicationContextRunner.java:363)
> > at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$run$0(AbstractApplicationContextRunner.java:341)
> > at org.springframework.boot.test.util.TestPropertyValues.lambda$applyToSystemProperties$1(TestPropertyValues.java:174)
> > at org.springframework.boot.test.util.TestPropertyValues.applyToSystemProperties(TestPropertyValues.java:188)
> > at org.springframework.boot.test.util.TestPropertyValues.applyToSystemProperties(TestPropertyValues.java:173)
> > at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$run$1(AbstractApplicationContextRunner.java:341)
> > at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.withContextClassLoader(AbstractApplicationContextRunner.java:369)
> > at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.run(AbstractApplicationContextRunner.java:340)
> > at dev.langchain4j.service.spring.mode.automatic.withTools.AiServicesAutoConfigIT.should_receive_ai_service_registered_event(AiServicesAutoConfigIT.java:82)
> > at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> > at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
> > at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

I found a bug in the previous PR, and I have submitted a new PR.

links here:
https://github.com/langchain4j/langchain4j-spring/pull/89

**Pull request closed without merging**
