### PR TITLE
Fix #2133 Spring boot starter breaks configuration classes

### PR DESCRIPTION
**Pull request by qing-wq**
Fixes https://github.com/langchain4j/langchain4j/issues/2133

The problem is `beanfactory.getBeanswithanNotation()`. It creates an instance of the Bean in advance.

https://github.com/langchain4j/langchain4j-spring/blob/405fddafbcf8c3463c7211dc82b7c5887f9531c6/langchain4j-spring-boot-starter/src/main/java/dev/langchain4j/service/spring/AiServiceScannerProcessor.java#L49

### CODE REVIEW

**Comment by langchain4j** [comment]
@qing-wq thanks a lot!
Could you please add a test that will prove that the bug was fixed? 🙏

**Comment by qing-wq** [comment]
@langchain4j certainly! I have completed the unit test

**Review by langchain4j — APPROVED** [review]
@qing-wq thanks a lot!

**Comment by davidb-e4s** [comment]
Hi Guys, 

Confirmed all working in my actual project using 0.37.0-SNAPSHOT

Thank you all so much for your help @langchain4j @qing-wq and others.

**Pull request merged**
